services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongodb:27017
      MONGO_DB_NAME: org_service
      JWT_SECRET_KEY: your-secret-key-change-in-production-32-chars-long
      ACCESS_TOKEN_EXPIRE_MINUTES: 15
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongodb_data:


networks:
  app-network:
    driver: bridge
